### ISSUE TITLE
🐛 Bug: (Windows) `Error: Command failed: gh auth token unknown command "token" for "gh auth"`

### ISSUE THREAD

**Issue by Jolg42** [Jolg42/pre-release-checks#1]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/Jolg42/pre-release-checks/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

`gh auth token` should work on Windows

### Actual

Logs from @janpio
```
Error: Command failed: gh auth token
unknown command "token" for "gh auth"
```

And it failed with a ugly error message after
```
  ◼ Check ecosystem-tests/test.yaml
file:///C:/Users/Jan/AppData/Local/npm-cache/_npx/39dd5ca412e8f8be/node_modules/@octokit/request/dist-bundle/index.js:138
    throw new RequestError(message, 500, {
          ^

RequestError [HttpError]: Headers.append: "token TypeError: Cannot read properties of undefined (reading 'options')
    at getAvailableArgsOnCmd (C:\Users\Jan\Documents\throwaway\prc\node_modules\gh\lib\cmd.js:203:33)
    at C:\Users\Jan\Documents\throwaway\prc\node_modules\gh\lib\cmd.js:164:22
    at Resolved.Resolved$interpret [as _interpret] (C:\Users\Jan\Documents\throwaway\prc\node_modules\fluture\index.js:663:5)
    at drain (C:\Users\Jan\Documents\throwaway\prc\node_modules\fluture\index.js:596:23)
    at settle (C:\Users\Jan\Documents\throwaway\prc\node_modules\fluture\index.js:509:17)
    at resolved (C:\Users\Jan\Documents\throwaway\prc\node_modules\fluture\index.js:525:7)
    at EncaseN3$res (C:\Users\Jan\Documents\throwaway\prc\node_modules\fluture\index.js:1550:11)
    at EncaseN$done (C:\Users\Jan\Documents\throwaway\prc\node_modules\fluture\index.js:1553:11)
    at FSReqCallback.oncomplete (node:fs:189:23)" is an invalid header value.
    at file:///C:/Users/Jan/AppData/Local/npm-cache/_npx/39dd5ca412e8f8be/node_modules/@octokit/request/dist-bundle/index.js:138:11
    at async requestWithGraphqlErrorHandling (file:///C:/Users/Jan/AppData/Local/npm-cache/_npx/39dd5ca412e8f8be/node_modules/@octokit/plugin-retry/dist-bundle/index.js:36:20)
    at async Job.doExecute (C:\Users\Jan\AppData\Local\npm-cache\_npx\39dd5ca412e8f8be\node_modules\bottleneck\light.js:405:18) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/prisma/prisma/actions/workflows/release-ci.yml/runs?branch=main&per_page=50',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/0.0.0-development octokit-core.js/6.1.2 Node.js/20.10.0 (win32; x64)',
      authorization: "token TypeError: Cannot read properties of undefined (reading 'options')\n" +
        '    at getAvailableArgsOnCmd (C:\\Users\\Jan\\Documents\\throwaway\\prc\\node_modules\\gh\\lib\\cmd.js:203:33)\n' +
        '    at C:\\Users\\Jan\\Documents\\throwaway\\prc\\node_modules\\gh\\lib\\cmd.js:164:22\n' +
        '    at Resolved.Resolved$interpret [as _interpret] (C:\\Users\\Jan\\Documents\\throwaway\\prc\\node_modules\\fluture\\index.js:663:5)\n' +
        '    at drain (C:\\Users\\Jan\\Documents\\throwaway\\prc\\node_modules\\fluture\\index.js:596:23)\n' +
        '    at settle (C:\\Users\\Jan\\Documents\\throwaway\\prc\\node_modules\\fluture\\index.js:509:17)\n' +
        '    at resolved (C:\\Users\\Jan\\Documents\\throwaway\\prc\\node_modules\\fluture\\index.js:525:7)\n' +
        '    at EncaseN3$res (C:\\Users\\Jan\\Documents\\throwaway\\prc\\node_modules\\fluture\\index.js:1550:11)\n' +
        '    at EncaseN$done (C:\\Users\\Jan\\Documents\\throwaway\\prc\\node_modules\\fluture\\index.js:1553:11)\n' +
        '    at FSReqCallback.oncomplete (node:fs:189:23)\n'
    },
    request: {
      hook: [Function: bound bound register],
      retryCount: 3,
      retries: 3,
      retryAfter: 16
    }
  },
  response: undefined
}

Node.js v20.10.0
```

**Comment by janpio** [comment]
`gh` is installed locally in the project as version `2.8.9`:
```
{
  "name": "prc",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "gh": "^2.8.9",
    "tsx": "^4.13.1"
  }
}
```

**Comment by janpio** [comment]
Can be closed, `gh` from Npm is something different and global `gh` was outdated and did not support `gh auth token`.
